<?php
return array(
    'base_url' => 'http://apis.siamits.dev/api/',
    'error_code'=>array(
        '0'    => 'Success',
        '1000' => 'Invalid token',
        '1001' => 'Connection error' ,
        '1002' => 'Invalid api key',
        '1003' => 'Invalid parameter',
        '1004' => 'Data not found',
        '1005' => 'Insert data error',
        '1006' => 'Update data error',
        '1007' => 'Delete data error',
        '1008' => 'Limit quota',
        '1009' => 'Permission denied',
        '1010' => 'Duplicate data',
        '1011' => 'Error register trueid',
        '1012' => 'Error register user',
        '1013' => 'Error Register store',
        '1014' => 'Activated',
        '1015' => 'Out of stock',
        '1016' => 'Cannot return some stocks',
        '1017' => 'Duplicate category name',

        '2000' => 'Debug value',
        '2001' => 'Error upload file',
        '2002' => 'No finle to upload',
        '2003' => 'Invalid token',
        '2004' => 'Invalid parameter',
        '2005' => 'File not found',
    ),
);
